/*
* Copyright (c) 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
*
* See the NOTICE file(s) distributed with this work for additional
* information regarding copyright ownership.
*
* This program and the accompanying materials are made available under the
* terms of the Apache License Version 2.0 which is available at
* https://www.apache.org/licenses/LICENSE-2.0
*
* SPDX-License-Identifier: Apache-2.0
*/

#![allow(missing_docs)]
use clap::{App, Arg};
use flexi_logger::{FileSpec, Logger};
use log::{error, info};
use std::{env, fs, path::PathBuf};

mod server_config;
mod sovd_server;

use server_config::ServerConfig as MainServerConfig;
use sovd_handlers::resolve_hostname;
use sovd_server::create;

//This logger use simple log info to output data into folder

fn init_logger(path: Option<&str>) -> Result<(), flexi_logger::FlexiLoggerError> {
    let log_path: PathBuf = match path {
        Some(p) if !p.is_empty() => {
            let custom_path = PathBuf::from(p);
            if !custom_path.exists() {
                fs::create_dir_all(&custom_path)?;
            }
            custom_path
        }
        _ => env::current_dir()?,
    };

    Logger::try_with_str("info")?
        .log_to_file(
            FileSpec::default()
                .directory(log_path)
                .basename("sovd_logs")
                .suffix("log"),
        )
        .format_for_files(flexi_logger::detailed_format)
        .duplicate_to_stdout(flexi_logger::Duplicate::Info)
        .duplicate_to_stderr(flexi_logger::Duplicate::Error)
        .print_message()
        .start()?;
    Ok(())
}

/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
#[tokio::main]
async fn main() {
    let matches = App::new("server")
        .arg(
            Arg::with_name("ip_address")
                .required(true)
                .index(1)
                .help("IP address"),
        )
        .arg(Arg::with_name("port").required(true).index(2).help("Port"))
        .arg(
            Arg::with_name("sovd_mode")
                .long("sovd-mode")
                .takes_value(true)
                .required(true)
                .possible_values(&["standalone", "gateway"])
                .help("SOVD mode (standalone or gateway)"),
        )
        .arg(
            Arg::with_name("hostname")
                .required(true)
                .index(3)
                .help("Hostname"),
        )
        .arg(
            Arg::with_name("logs")
                .required(false)
                .index(4)
                .help("Logs location"),
        )
        .get_matches();
    let log_path = matches.value_of("logs");

    if let Err(e) = init_logger(log_path) {
        info!("Logger initialization failed: {}", e);
    }

    let ip_address_name = matches.value_of("ip_address").unwrap().to_string();
    let port = matches.value_of("port").unwrap().to_string();
    let protocol = "http".to_string(); //Value hardcoded because currently just HTTP is supported
    let sovd_mode = matches.value_of("sovd_mode").unwrap().to_string();
    let host_name = matches.value_of("hostname").unwrap().to_string();

    let ip_address =
        resolve_hostname(&ip_address_name).expect("Failed to resolve hostname or IP address");

    // Get the path to the current executable
    let exe_path = env::current_exe().expect("Failed to get current executable path");
    info!("Exe path: {:?}", exe_path);
    // Concatenate the path to the configuration file
    let config_path = exe_path.parent().unwrap().join("sovd_server_apps.conf");
    info!("Config path: {:?}", config_path);

    let server_config = MainServerConfig::create_server_settings(
        config_path.to_str().unwrap(),
        protocol.clone(),
        ip_address.clone(),
        port.clone(),
        sovd_mode.clone(),
        host_name.clone(),
    );
    match server_config {
        Ok(server_config) => {
            info!("Server configuration created successfully.");
            info!("Protocol: {}", server_config.get_protocol());
            info!("IP Address: {}", server_config.get_ip_address());
            info!("Port: {}", server_config.get_port());
            info!("Base URI: {}", server_config.get_base_uri());
            info!("SOVD Mode: {}", server_config.get_sovd_mode());

            // Printing Config Entries
            info!("Config Entries:");
            for entry in server_config.get_config_entries() {
                info!("Component: {}", entry.component_id);
                for app in &entry.apps {
                    info!("App: {}", app);
                }
            }

            let address = format!("{}:{}", ip_address, port);
            info!("Starting SOVD server: {}", ip_address);
            create(&server_config, &address).await;
        }
        Err(err) => {
            error!(
                "Failed to create server configuration. Server could not be started: {:?}",
                err
            );
        }
    }
}
